version: '3'
services:
  db:
    image: mysql
    env_file: .env
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: rails s -p 80 -b 'web'
    volumes:
      - .:/web
    ports:
      - "80:80"
    depends_on:
      - db
    env_file: .env
